version: "2"

services: 
  apache: 
    image: webdevops/php-apache:centos-7
    volumes: 
      - ./wordpress:/app
    links: 
      - mariadb:db
  mariadb: 
    image: centos/mariadb-101-centos7
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress 
      - MYSQL_PASSWORD=wordpress

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin 
    ports: 
      - "8082:80" 
    links: 
      - mariadb:db
  lb: 
    image: dockercloud/haproxy:latest
    links: 
      - apache
    ports: 
      - "80:80"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock


